version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=blog_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blog_user -d blog"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: sh -c "./wait-for-it.sh db && python manage.py migrate && python manage.py loaddata blog/fixtures/*.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://blog_user:blog_password@db:5432/blog
      - POSTGRES_PASSWORD=blog_password
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: 